import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import localFont from "next/font/local";
import "./globals.css";

// Local Fonts (already in your code)
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata (this is fine)
export const metadata = {
  title: "Quantum",
  description: "Generated by create next app",

  icons: {
    icon: "/favicon.ico",
  },

  link: [
    {
      rel: "stylesheet",
      href: "https://fonts.googleapis.com/css2?family=Fraunces:wght@400;700&display=swap",
    },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-serif`} // Adding font-serif here
        style={{ fontFamily: "'Fraunces', serif" }} // Apply Fraunces as fallback
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
